# Generated by Django 5.0.7 on 2024-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('show', 'Show'), ('theatre', 'Apresentação Teatral'), ('orchestra', 'Orquestra'), ('musical', 'Musical'), ('comedy', 'Show de Humor')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
