# Generated by Django 5.0.7 on 2024-08-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cultural_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultural_event',
            name='is_free',
        ),
    ]
